# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: seeeduino_xiao
    shield: hummingbird
  - board: seeeduino_xiao_ble
    shield: hummingbird
  - board: seeeduino_xiao_rp2040
    shield: hummingbird
  - board: seeeduino_xiao
    shield: tern
  # - board: nice_nano_v2
  #   shield: naked48
  - board: nice_nano_v2
    shield: chocv 
  - board: nice_nano_v2
    shield: cradio_left
  - board: nice_nano_v2
    shield: cradio_right
  - board: nice_nano_v2
    shield: gnat_left
  - board: nice_nano_v2
    shield: gnat_right
  - board: nice_nano_v2
    shield: osprette
  - board: nice_nano_v2
    shield: settings_reset
